#define CHECK_INTERVAL 60

#define CRITICAL_BAT_LEVEL 5
#define WARN_BAT_LEVEL 20
#define INFORM_BAT_LEVEL 30

#define CRITICAL_BAT_LEVEL_INFO_TIMEOUT_SEC 600
#define WARN_BAT_LEVEL_INFO_TIMEOUT_SEC 60
#define INFORM_BAT_LEVEL_INFO_TIMEOUT_SEC 20
